#-----------------------------------------------------------------------------
# File:    Makefile.srcs
#
# Author:  Ian Buckley, Ion Concepts LLC
#
# Description: Synthesizable System Verilog Source Code For Makefile Driven Flows
#
# License: CERN-OHL-P (See LICENSE.md)
#
#-----------------------------------------------------------------------------

DIRT_GLOBAL_SRCS = $(abspath $(addprefix $(DIRT_DIR)/lib/axis/, \
drat_protocol.sv \
))