#-----------------------------------------------------------------------------
# File:    Makefile.srcs
#
# Author:  Ian Buckley, Ion Concepts LLC
#
# Description: Synthesizable System Verilog Source Code For Makefile Driven Flows
#
# License: CERN-OHL-P (See LICENSE.md)
#
#-----------------------------------------------------------------------------

DIRT_DSP_SRCS = $(abspath $(addprefix $(DIRT_DIR)/lib/dsp/, \
dsp_1_channel.sv \
dsp_rx.sv \
dsp_tx.sv \
dsp_loopback.sv \
))
