#-----------------------------------------------------------------------------
# File:    Makefile.srcs
#
# Author:  Ian Buckley, Ion Concepts LLC
#
# Description: Synthesizable System Verilog Source Code For Makefile Driven Flows
#
# License: CERN-OHL-P (See LICENSE.md)
#
#-----------------------------------------------------------------------------

DIRT_ETHERNET_SRCS = $(abspath $(addprefix $(DIRT_DIR)/lib/axis/, \
drat2eth_framer.sv \
eth_classifier_2_egress.sv \
ethernet.sv
